/**
 * LoveLetterModal — Feature F46: Love Letters
 *
 * Modal viewer for love letters generated by the character. Displays
 * the letter in a warm, handwritten-feel card with depth level info
 * and bond context. Bond-gated: requires bond >= 40.
 *
 * API surface:
 *   POST /api/characters/{id}/love-letter → { ok, letter: { char_name, bond_level, depth_level, prompt } }
 *
 * The `prompt` field is the character's letter text template which
 * gets rendered as the letter body. In the future this will be sent
 * through the LLM for personalization — for now it's displayed as-is.
 *
 * @module LoveLetterModal
 */

import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X, Heart, Loader2, Mail, Sparkles,
} from 'lucide-react';

/* ═══════════════════════════════════════════════════════════════════════
   Types
   ═══════════════════════════════════════════════════════════════════════ */

/** Love letter data returned by the backend. */
interface LoveLetter {
  char_name: string;
  bond_level: number;
  depth_level: string;
  prompt: string;
}

interface LoveLetterModalProps {
  /** Whether the modal is visible. */
  isOpen: boolean;
  /** Callback to close the modal. */
  onClose: () => void;
  /** Character database ID. */
  characterId: number;
  /** Character display name. */
  characterName: string;
}

/* ═══════════════════════════════════════════════════════════════════════
   Depth level styling
   ═══════════════════════════════════════════════════════════════════════ */

const DEPTH_STYLES: Record<string, { label: string; color: string; bg: string }> = {
  shy:        { label: 'Shy',        color: '#3b82f6', bg: 'rgba(59, 130, 246, 0.08)' },
  warm:       { label: 'Warm',       color: '#22c55e', bg: 'rgba(34, 197, 94, 0.08)' },
  passionate: { label: 'Passionate', color: '#ef4444', bg: 'rgba(239, 68, 68, 0.08)' },
  devoted:    { label: 'Devoted',    color: '#a855f7', bg: 'rgba(168, 85, 247, 0.08)' },
  soulmate:   { label: 'Soulmate',   color: '#f43f5e', bg: 'rgba(244, 63, 94, 0.08)' },
};

/* ═══════════════════════════════════════════════════════════════════════
   Component
   ═══════════════════════════════════════════════════════════════════════ */

/**
 * A modal that generates and displays a love letter from the character.
 * The letter is presented in a warm, card-like design with a subtle
 * parchment aesthetic. Users trigger generation by opening the modal.
 *
 * @param props - See {@link LoveLetterModalProps}.
 *
 * @example
 * <LoveLetterModal
 *   isOpen={showLetter}
 *   onClose={() => setShowLetter(false)}
 *   characterId={5}
 *   characterName="Luna"
 * />
 */
export function LoveLetterModal({
  isOpen,
  onClose,
  characterId,
  characterName,
}: LoveLetterModalProps) {
  const [letter, setLetter] = useState<LoveLetter | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /* ── Generate letter on open ─────────────────────────────────────── */

  const generateLetter = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/characters/${characterId}/love-letter`, {
        method: 'POST',
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (data.ok) {
        setLetter(data.letter);
      } else {
        setError(data.error || 'Failed to generate letter');
      }
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }, [characterId]);

  /* ── Generate on first open ──────────────────────────────────────── */

  const handleOpen = useCallback(() => {
    if (!letter && !loading) generateLetter();
  }, [letter, loading, generateLetter]);

  // Trigger generation when modal opens
  if (isOpen && !letter && !loading && !error) {
    handleOpen();
  }

  /* ── Reset on close ──────────────────────────────────────────────── */

  const handleClose = () => {
    onClose();
    // Keep the letter cached — user might reopen to re-read
  };

  /* ── Depth styling ───────────────────────────────────────────────── */

  const depthStyle = letter
    ? DEPTH_STYLES[letter.depth_level] ?? DEPTH_STYLES.warm
    : DEPTH_STYLES.warm;

  /* ── Render ──────────────────────────────────────────────────────── */

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            className="fixed inset-0 z-[200]"
            style={{ backgroundColor: 'rgba(0,0,0,0.55)' }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleClose}
          />

          {/* Letter card — centered */}
          <motion.div
            className="fixed z-[201] flex flex-col overflow-hidden"
            style={{
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              width: 'min(480px, 90vw)',
              maxHeight: '80vh',
              backgroundColor: 'var(--color-surface)',
              borderRadius: 'var(--radius-card)',
              boxShadow: 'var(--shadow-elevated)',
              border: '1px solid var(--color-border-subtle)',
            }}
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          >
            {/* ── Header ──────────────────────────────────────────── */}
            <div
              className="flex items-center justify-between px-5 py-3"
              style={{ borderBottom: '1px solid var(--color-border-subtle)' }}
            >
              <div className="flex items-center gap-2">
                <Mail size={16} style={{ color: 'var(--color-accent)' }} />
                <h2 className="text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>
                  A Letter from {characterName}
                </h2>
              </div>
              <button
                onClick={handleClose}
                className="p-1 rounded-md hover:opacity-80 transition-opacity"
                style={{ color: 'var(--color-text-secondary)' }}
                aria-label="Close letter"
              >
                <X size={16} />
              </button>
            </div>

            {/* ── Body ────────────────────────────────────────────── */}
            <div className="flex-1 overflow-y-auto px-6 py-5">
              {/* Loading state */}
              {loading && (
                <div className="flex flex-col items-center justify-center py-12 gap-3">
                  <Loader2 size={24} className="animate-spin" style={{ color: 'var(--color-accent)' }} />
                  <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                    {characterName} is writing...
                  </p>
                </div>
              )}

              {/* Error state */}
              {error && (
                <div className="flex flex-col items-center justify-center py-12 gap-3">
                  <Heart size={24} style={{ color: 'var(--color-text-muted)', opacity: 0.4 }} />
                  <p className="text-xs text-center" style={{ color: 'var(--color-text-muted)' }}>
                    {error}
                  </p>
                  <button
                    onClick={generateLetter}
                    className="text-xs px-3 py-1.5 rounded-md"
                    style={{
                      backgroundColor: 'var(--color-accent-soft)',
                      color: 'var(--color-accent)',
                    }}
                  >
                    Try Again
                  </button>
                </div>
              )}

              {/* Letter content */}
              {letter && !loading && (
                <div className="space-y-4">
                  {/* Depth badge */}
                  <div className="flex items-center gap-2">
                    <Sparkles size={12} style={{ color: depthStyle.color }} />
                    <span
                      className="text-xs px-2 py-0.5 rounded-full"
                      style={{ backgroundColor: depthStyle.bg, color: depthStyle.color }}
                    >
                      {depthStyle.label} — Bond Level {letter.bond_level}
                    </span>
                  </div>

                  {/* Letter text */}
                  <div
                    className="rounded-lg p-5"
                    style={{
                      backgroundColor: 'var(--color-surface-raised)',
                      border: '1px solid var(--color-border-subtle)',
                      // Subtle warm tint for parchment feel
                      backgroundImage: 'linear-gradient(135deg, transparent, rgba(251, 191, 36, 0.02))',
                    }}
                  >
                    <p
                      className="text-sm leading-relaxed whitespace-pre-wrap"
                      style={{
                        color: 'var(--color-text-primary)',
                        fontStyle: 'italic',
                        lineHeight: 1.8,
                      }}
                    >
                      {letter.prompt}
                    </p>
                  </div>

                  {/* Signature */}
                  <div className="flex justify-end pr-4">
                    <p
                      className="text-sm"
                      style={{
                        color: 'var(--color-accent)',
                        fontStyle: 'italic',
                      }}
                    >
                      — {letter.char_name}
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* ── Footer ──────────────────────────────────────────── */}
            {letter && !loading && (
              <div
                className="flex items-center justify-between px-5 py-3"
                style={{ borderTop: '1px solid var(--color-border-subtle)' }}
              >
                <button
                  onClick={generateLetter}
                  className="text-xs px-3 py-1.5 rounded-md transition-opacity hover:opacity-80"
                  style={{
                    backgroundColor: 'var(--color-accent-soft)',
                    color: 'var(--color-accent)',
                  }}
                >
                  Request New Letter
                </button>
                <button
                  onClick={handleClose}
                  className="text-xs px-3 py-1.5 rounded-md transition-opacity hover:opacity-80"
                  style={{
                    backgroundColor: 'var(--color-surface-raised)',
                    color: 'var(--color-text-secondary)',
                    border: '1px solid var(--color-border)',
                  }}
                >
                  Close
                </button>
              </div>
            )}
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
