/**
 * SceneReplayViewer — Feature F35: Scene Replay from Character POV
 *
 * Modal viewer that presents a past intimate scene re-narrated from
 * the character's perspective. Takes scene replay data and displays it
 * in a scrollable, diary-like format with mood indicators and
 * character-voice commentary.
 *
 * This is primarily a display component — the actual scene replay data
 * is generated by the backend when the user requests a replay of a
 * past session.
 *
 * @module SceneReplayViewer
 */

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X, Play, BookOpen, Loader2, ChevronLeft, ChevronRight,
} from 'lucide-react';

/* ═══════════════════════════════════════════════════════════════════════
   Types
   ═══════════════════════════════════════════════════════════════════════ */

/** A single scene segment in the replay. */
interface ReplaySegment {
  type: 'narration' | 'dialogue' | 'thought' | 'description';
  text: string;
  mood?: string;
  intensity?: number;
}

/** Full scene replay data. */
interface SceneReplay {
  title: string;
  characterName: string;
  originalDate: string;
  segments: ReplaySegment[];
  overallMood: string;
}

interface SceneReplayViewerProps {
  /** Whether the viewer is visible. */
  isOpen: boolean;
  /** Callback to close the viewer. */
  onClose: () => void;
  /** Scene replay data to display. Null shows a "no replay" state. */
  replay: SceneReplay | null;
  /** Whether replay data is being loaded. */
  loading?: boolean;
}

/* ═══════════════════════════════════════════════════════════════════════
   Constants
   ═══════════════════════════════════════════════════════════════════════ */

const SEGMENT_STYLES: Record<string, { style: React.CSSProperties; prefix: string }> = {
  narration: {
    style: { fontStyle: 'italic', color: 'var(--color-text-secondary)' },
    prefix: '',
  },
  dialogue: {
    style: { color: 'var(--color-text-primary)', fontWeight: 500 },
    prefix: '"',
  },
  thought: {
    style: { fontStyle: 'italic', color: 'var(--color-accent)', opacity: 0.9 },
    prefix: '',
  },
  description: {
    style: { color: 'var(--color-text-secondary)', fontSize: '0.8rem' },
    prefix: '',
  },
};

/* ═══════════════════════════════════════════════════════════════════════
   Component
   ═══════════════════════════════════════════════════════════════════════ */

/**
 * Modal viewer for scene replays narrated from the character's POV.
 * Segments are displayed sequentially with type-specific styling
 * (narration in italics, dialogue in quotes, thoughts in accent color).
 * Supports page-by-page navigation through long replays.
 *
 * @param props - See {@link SceneReplayViewerProps}.
 *
 * @example
 * <SceneReplayViewer
 *   isOpen={showReplay}
 *   onClose={() => setShowReplay(false)}
 *   replay={replayData}
 *   loading={replayLoading}
 * />
 */
export function SceneReplayViewer({
  isOpen,
  onClose,
  replay,
  loading = false,
}: SceneReplayViewerProps) {
  const [page, setPage] = useState(0);
  const SEGMENTS_PER_PAGE = 8;

  // Pagination
  const segments = replay?.segments ?? [];
  const totalPages = Math.ceil(segments.length / SEGMENTS_PER_PAGE);
  const pageSegments = segments.slice(
    page * SEGMENTS_PER_PAGE,
    (page + 1) * SEGMENTS_PER_PAGE,
  );

  const formatDate = (iso: string) => {
    try {
      return new Date(iso).toLocaleDateString(undefined, {
        weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
      });
    } catch {
      return iso;
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            className="fixed inset-0 z-[200]"
            style={{ backgroundColor: 'rgba(0,0,0,0.55)' }}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
          />

          {/* Viewer card — centered */}
          <motion.div
            className="fixed z-[201] flex flex-col overflow-hidden"
            style={{
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              width: 'min(560px, 90vw)',
              maxHeight: '85vh',
              backgroundColor: 'var(--color-surface)',
              borderRadius: 'var(--radius-card)',
              boxShadow: 'var(--shadow-elevated)',
              border: '1px solid var(--color-border-subtle)',
            }}
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          >
            {/* ── Header ──────────────────────────────────────────── */}
            <div
              className="flex items-center justify-between px-5 py-3"
              style={{ borderBottom: '1px solid var(--color-border-subtle)' }}
            >
              <div className="flex items-center gap-2">
                <BookOpen size={16} style={{ color: 'var(--color-accent)' }} />
                <h2 className="text-sm font-semibold" style={{ color: 'var(--color-text-primary)' }}>
                  {replay ? `${replay.characterName}'s Perspective` : 'Scene Replay'}
                </h2>
              </div>
              <button
                onClick={onClose}
                className="p-1 rounded-md hover:opacity-80 transition-opacity"
                style={{ color: 'var(--color-text-secondary)' }}
                aria-label="Close replay"
              >
                <X size={16} />
              </button>
            </div>

            {/* ── Body ────────────────────────────────────────────── */}
            <div className="flex-1 overflow-y-auto px-6 py-5">
              {/* Loading */}
              {loading && (
                <div className="flex flex-col items-center justify-center py-16 gap-3">
                  <Loader2 size={24} className="animate-spin" style={{ color: 'var(--color-accent)' }} />
                  <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                    Replaying the scene...
                  </p>
                </div>
              )}

              {/* No replay data */}
              {!loading && !replay && (
                <div className="flex flex-col items-center justify-center py-16 gap-3">
                  <Play size={28} style={{ color: 'var(--color-text-muted)', opacity: 0.4 }} />
                  <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                    No scene replay available
                  </p>
                </div>
              )}

              {/* Replay content */}
              {!loading && replay && (
                <div className="space-y-4">
                  {/* Scene title & date */}
                  <div className="mb-4">
                    <h3 className="text-base font-semibold" style={{ color: 'var(--color-text-primary)' }}>
                      {replay.title}
                    </h3>
                    <p className="text-xs mt-0.5" style={{ color: 'var(--color-text-muted)' }}>
                      {formatDate(replay.originalDate)}
                      {replay.overallMood && (
                        <span className="ml-2 capitalize">— {replay.overallMood}</span>
                      )}
                    </p>
                  </div>

                  {/* Segments */}
                  {pageSegments.map((seg, i) => {
                    const segStyle = SEGMENT_STYLES[seg.type] ?? SEGMENT_STYLES.narration;
                    return (
                      <motion.div
                        key={page * SEGMENTS_PER_PAGE + i}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.05 }}
                        className="rounded-lg p-4"
                        style={{
                          backgroundColor: seg.type === 'thought'
                            ? 'var(--color-accent-soft)'
                            : 'var(--color-surface-raised)',
                          border: '1px solid var(--color-border-subtle)',
                        }}
                      >
                        {seg.type !== 'narration' && (
                          <span
                            className="text-xs uppercase tracking-wider block mb-1"
                            style={{ color: 'var(--color-text-muted)', fontSize: '0.55rem' }}
                          >
                            {seg.type}
                          </span>
                        )}
                        <p
                          className="text-sm leading-relaxed whitespace-pre-wrap"
                          style={segStyle.style}
                        >
                          {segStyle.prefix}{seg.text}{seg.type === 'dialogue' ? '"' : ''}
                        </p>
                      </motion.div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* ── Footer with pagination ──────────────────────────── */}
            {!loading && replay && totalPages > 1 && (
              <div
                className="flex items-center justify-between px-5 py-3"
                style={{ borderTop: '1px solid var(--color-border-subtle)' }}
              >
                <button
                  onClick={() => setPage(p => Math.max(0, p - 1))}
                  disabled={page === 0}
                  className="flex items-center gap-1 text-xs px-2 py-1 rounded transition-opacity"
                  style={{
                    color: page === 0 ? 'var(--color-text-muted)' : 'var(--color-accent)',
                    opacity: page === 0 ? 0.4 : 1,
                  }}
                >
                  <ChevronLeft size={14} />
                  Previous
                </button>
                <span className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                  {page + 1} / {totalPages}
                </span>
                <button
                  onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
                  disabled={page >= totalPages - 1}
                  className="flex items-center gap-1 text-xs px-2 py-1 rounded transition-opacity"
                  style={{
                    color: page >= totalPages - 1 ? 'var(--color-text-muted)' : 'var(--color-accent)',
                    opacity: page >= totalPages - 1 ? 0.4 : 1,
                  }}
                >
                  Next
                  <ChevronRight size={14} />
                </button>
              </div>
            )}
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
