import { useEffect } from 'react';
import { create } from 'zustand';
import { AnimatePresence, motion } from 'framer-motion';
import { X } from 'lucide-react';

/* ── Types ────────────────────────────────────────────────────────────── */

/** A single toast notification entry. */
export interface Toast {
  /** Unique identifier (auto-generated by addToast). */
  id: string;
  /** Primary text displayed in the toast. */
  message: string;
  /** Optional emoji or icon string rendered before the message. */
  icon?: string;
  /** Visual variant — controls accent color. Defaults to 'info'. */
  type?: 'info' | 'success' | 'warning';
  /** Callback fired when the user clicks the toast body. */
  onClick?: () => void;
  /** Auto-dismiss delay in ms. Defaults to 4000. */
  duration?: number;
}

interface ToastState {
  toasts: Toast[];
  /** Queue a new toast. An `id` is generated automatically. */
  addToast: (toast: Omit<Toast, 'id'>) => void;
  /** Remove a toast by id (called on dismiss or auto-expire). */
  removeToast: (id: string) => void;
}

/** Maximum number of toasts visible simultaneously. */
const MAX_VISIBLE = 3;

/** Default auto-dismiss delay in milliseconds. */
const DEFAULT_DURATION = 2500;

/* ── Store ────────────────────────────────────────────────────────────── */

let _nextId = 0;

/**
 * Global toast store. Import `useToastStore` anywhere to enqueue
 * notifications via `addToast({ message, type?, icon?, duration? })`.
 */
export const useToastStore = create<ToastState>((set) => ({
  toasts: [],

  addToast: (toast) => {
    const id = `toast-${Date.now()}-${_nextId++}`;
    set((s) => {
      const next = [...s.toasts, { ...toast, id }];
      // Evict oldest when exceeding the visible cap
      return { toasts: next.length > MAX_VISIBLE ? next.slice(next.length - MAX_VISIBLE) : next };
    });
  },

  removeToast: (id) =>
    set((s) => ({ toasts: s.toasts.filter((t) => t.id !== id) })),
}));

/* ── Accent colors per type ───────────────────────────────────────────── */

const ACCENT: Record<string, string> = {
  info: 'var(--color-primary, #6366f1)',
  success: '#22c55e',
  warning: '#f59e0b',
};

/* ── Component ────────────────────────────────────────────────────────── */

/**
 * Renders the global toast queue as a fixed overlay in the top-right corner.
 *
 * Mount once at the app root (e.g. inside `<App />`). Toasts are enqueued
 * from anywhere via `useToastStore.getState().addToast(...)`.
 *
 * @example
 * // Enqueue from a non-React context:
 * import { useToastStore } from './components/ToastQueue';
 * useToastStore.getState().addToast({
 *   message: 'Qwen3: Reasoning, Tools enabled',
 *   type: 'success',
 *   icon: '🧠',
 * });
 */
export function ToastQueue() {
  const toasts = useToastStore((s) => s.toasts);

  return (
    <div
      style={{
        position: 'fixed',
        bottom: 16,
        right: 16,
        zIndex: 9000,
        display: 'flex',
        flexDirection: 'column-reverse',
        gap: 6,
        pointerEvents: 'none',
      }}
    >
      <AnimatePresence mode="popLayout">
        {toasts.map((toast) => (
          <ToastItem key={toast.id} toast={toast} />
        ))}
      </AnimatePresence>
    </div>
  );
}

/* ── Individual toast ─────────────────────────────────────────────────── */

/**
 * A single toast notification with auto-dismiss timer.
 *
 * @param props.toast - The toast data to render
 */
function ToastItem({ toast }: { toast: Toast }) {
  const removeToast = useToastStore((s) => s.removeToast);

  // Auto-dismiss after the configured duration
  useEffect(() => {
    const timeout = setTimeout(
      () => removeToast(toast.id),
      toast.duration ?? DEFAULT_DURATION,
    );
    return () => clearTimeout(timeout);
  }, [toast.id, toast.duration, removeToast]);

  const accentColor = ACCENT[toast.type ?? 'info'];

  /**
   * Handle click on the toast body — invoke the optional callback
   * and then dismiss the toast.
   */
  const handleClick = () => {
    toast.onClick?.();
    removeToast(toast.id);
  };

  return (
    <motion.div
      layout
      initial={{ opacity: 0, x: 80, scale: 0.95 }}
      animate={{ opacity: 1, x: 0, scale: 1 }}
      exit={{ opacity: 0, x: 80, scale: 0.95 }}
      transition={{ type: 'spring', damping: 20, stiffness: 300 }}
      onClick={handleClick}
      style={{
        pointerEvents: 'auto',
        maxWidth: 260,
        padding: '6px 10px',
        borderRadius: 8,
        background: 'var(--color-surface)',
        border: '1px solid var(--color-border-subtle)',
        borderLeft: `2px solid ${accentColor}`,
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
        color: 'var(--color-text-secondary)',
        fontSize: '0.68rem',
        fontWeight: 500,
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        cursor: toast.onClick ? 'pointer' : 'default',
        userSelect: 'none',
      }}
    >
      {toast.icon && <span style={{ fontSize: '1rem', flexShrink: 0 }}>{toast.icon}</span>}

      <span style={{ flex: 1, lineHeight: 1.35 }}>{toast.message}</span>

      <button
        onClick={(e) => {
          e.stopPropagation();
          removeToast(toast.id);
        }}
        style={{
          background: 'none',
          border: 'none',
          padding: 2,
          cursor: 'pointer',
          color: 'var(--color-text-secondary, #999)',
          flexShrink: 0,
          display: 'flex',
          alignItems: 'center',
        }}
        aria-label="Dismiss toast"
      >
        <X size={12} />
      </button>
    </motion.div>
  );
}
